name: pages-auto-build-deploy
on:
  # workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #     # Runs everyday at 8:00 AM
  #     - cron: "0 8 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.117.0"

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.HUGO_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_dir: ./public